apiVersion: elasticsearchnativerealm.ckpd.co/v1
kind: ElasticsearchNativeRealmUser
metadata:
  namespace: elasticsearch
  name: custom-user
spec:
  user:
    username: custom-user
    roles: [viewer]
    email: custom-user@example.com
  secretName: elasticsearch-custom-user-credentials
