apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticsearch-native-realm-operator
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  # - apiGroups: [kopf.dev]
  #   resources: [clusterkopfpeerings]
  #   verbs: [list, watch, patch, get]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  # Application: creating secrets for generated credentials
  - apiGroups: [""]
    resources: [secrets]
    verbs: [create]

  # Application: read and handling access for watching cluster-wide.
  - apiGroups: [elasticsearchnativerealm.ckpd.co]
    resources: [elasticsearchnativerealmusers]
    verbs: [list, watch, patch]
