apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elasticsearch-native-realm-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elasticsearch-native-realm-operator
subjects:
  - kind: ServiceAccount
    name: native-realm-operator
    namespace: elastic-system
