apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds.yaml
  - cluster-role-binding.yaml
  - cluster-role.yaml
  - deployment.yaml
  - namespace.yaml
  - service-account.yaml
